version: "3.8"

services:
  api:
    build:
      context: ./
    ports:
      - "8082:8082"
    depends_on:
      - database

  database:
    hostname: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: traccar
    ports:
      - "3306:3306"
